### ISSUE TITLE
U+11241 KHOJKI VOWEL SIGN VOCALIC R not rendering in Noto Sans Khojki

### ISSUE THREAD

**Issue by EkiRahardian** [notofonts/khojki#26]
### Font 
  > NotoSansKhojki-Regular.ttf

### Where the font came from, and when
  > https://notofonts.github.io/khojki/fonts/NotoSansKhojki/full/ttf/NotoSansKhojki-Regular.ttf
  > 01 September 2023

### Font Version
  > 2.003; ttfautohint (v1.8.4.7-5d5b)

### OS name and version
  > Windows 11

### Application name and version
  > Google Chrome

### Issue
  > U+11241 KHOJKI VOWEL SIGN VOCALIC R still showing a blank box when using Noto Sans Khojki

### Character data
  > 𑉁 U+11241 KHOJKI VOWEL SIGN VOCALIC R

### Screenshot
  > Result
  > ![image](https://github.com/notofonts/khojki/assets/23203226/79b8bc07-09a9-4e78-888b-18b8ba0d6569)
  > Expected result
  > ![image](https://github.com/notofonts/khojki/assets/23203226/82ea7e74-e47a-427e-bbad-491521546bbc)

**Comment by simoncozens** [comment]
I'm not surprised by this. The character has been added to the sources in the repository, but we don't automatically do a release of every font every month; the monthly Noto release just collects the latest releases of everything so that downstream users can easily pick up the latest stuff.

We work on a quarterly release cycle, and have a focus on a certain set of fonts for each quarter. I expect a new Khojki release at the end of the year. If you need it earlier, grab pre-releases from https://notofonts.github.io/khojki/.
